### ISSUE TITLE
ViewControllerを削除する

### ISSUE THREAD

**Issue by sakiyamaK** [haruusagi/ToDoList#1]
使わないコードはなるべく消しましょう

・余計なバグやビルドエラーを産む
・ビルドに時間がかかる
・ファイルが増えると作業に時間がかかる

**Comment by haruusagi** [comment]
遅くなりました。。。
ありがとうございます！！！

**Comment by sakiyamaK** [comment]
@haruusagi をつけるとわかりやすくなります
